Log_09_Account/Areas/ACC/Controllers/ACC_AccountController.cs
using System.Data;
using Log_09_Account.Areas.ACC.Models;
using Log_09_Account.BAL.ACC_Account;
using Log_09_Account.CF;
using Log_09_Account.DAL;
using Microsoft.AspNetCore.Mvc;

namespace Log_09_Account.Areas.ACC.Controllers
{
    // [CheckAccess]
    [Area("ACC")]
    [Route("[Controller]/[action]")]
    public class ACC_AccountController : Controller
    {
        #region 10.0 Local Variables
        ACC_AccountBAL balACC_Account = new ACC_AccountBAL();
        #endregion 10.0 Local Variables

        #region List Page Methods

        #region Index
        public IActionResult Index()
        {
            FillDropDownList();
            return View();
        }
        #endregion

        #region Search Result
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult _SearchResult(ACC_AccountModel modelACC_Account)
        {
            UserOperationRightsModel vUserOperationRightsModel = UserOperationRights.CheckForOperation(ControllerContext);
            ViewBag.UserOperationRights = vUserOperationRightsModel;

            #region 12.2 Set Default Value
            ViewBag.SearchResultHeaderText = CV.SearchResultHeaderText;

            modelACC_Account.F_PageNo = modelACC_Account.F_PageNo == null ? 1 : modelACC_Account.F_PageNo;
            modelACC_Account.F_PageSize = modelACC_Account.F_PageSize == null ? 25 : modelACC_Account.F_PageSize;
            #endregion 12.2 Set Default Value            

            //modelACC_Account.F_PageNo = 1;
            //modelACC_Account.F_PageSize = 25;

            //lisyt<resultmodel>
            var vChapterList = balACC_Account.dbo_PR_ACC_Account_SelectAll(modelACC_Account);

            PagedListPagerModel vPagedListPager = new PagedListPagerModel(vChapterList.First().TotalRecords, Convert.ToInt32(modelACC_Account.F_PageNo), Convert.ToInt32(modelACC_Account.F_PageSize));
            vPagedListPager.PageInfo = Pagination.GetPageInformation(vPagedListPager);
            vPagedListPager.PageSizeList = Pagination.GetPagedListPageSizes();

            var vModel = new Tuple<ACC_AccountModel, PagedListPagerModel, List<dbo_PR_ACC_Account_SelectAll_Result>>(modelACC_Account, vPagedListPager, vChapterList);

            return PartialView("_ACC_AccountList", vModel);
        }
        #endregion Search Result

        #region ExportExcel
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ExportExcel(ACC_AccountModel modelACC_Account, int TotalRecords)
        {
            UserOperationRightsModel vUserOperationRightsModel = UserOperationRights.CheckForOperation(ControllerContext);
            ViewBag.UserOperationRights = vUserOperationRightsModel;

            modelACC_Account.F_PageNo = 1;
            modelACC_Account.F_PageSize = TotalRecords;
            var vAccountList = balACC_Account.dbo_PR_ACC_Account_SelectAll(modelACC_Account);

            DataTable dt = EntityToDataTable.ConvertToDataTable(vAccountList);

            var contentType = "application/vnmodelACC_Account.openxmlformats-officedocument.spreadsheetml.sheet";
            var fileName = "AccountList.xlsx";

            return File(CommonFunctions.DownloadExcel(dt, "Chapter").ToArray(), contentType, fileName);
        }
        #endregion ExportExcel

        #region _Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult _Delete(int AccountID)
        {
            bool vReturen = balACC_Account.dbo_PR_ACC_Account_Delete(AccountID);
            return RedirectToAction("Index");
        }
        #endregion

        #endregion

        #region FillLabels
        private void FillLabels(ControllerContext controllerContext)
        {
            var CurrentArea = controllerContext.RouteData.Values["area"].ToString();
            var CurrentController = controllerContext.RouteData.Values["controller"].ToString();
            var CurrentAction = controllerContext.RouteData.Values["action"].ToString();
            ViewBag.lblAccountName = "Account";
        }
        #endregion FillLabels

        #region Fill DropDown List
        private void FillDropDownList()
        {
            ViewBag.AccountGroupList = CommonFillMethods.FillDropDownListAccountGroupID();
            ViewBag.AccountTypeList = CommonFillMethods.FillDropDownListAccountTypeID();
        }
        #endregion

        #region 11.0 Page Load Event - Add/Edit
        public IActionResult AddEdit(int? AccountID)
        {

            #region 11.2 IsAdd, IsEdit Rights
            UserOperationRightsModel vUserOperationRightsModel = UserOperationRights.CheckForOperation(ControllerContext);
            ViewBag.UserOperationRights = vUserOperationRightsModel;

            if (!vUserOperationRightsModel.IsAdd && !vUserOperationRightsModel.IsEdit)
            {
                return RedirectToAction("Index", "Error", new { Area = "" });
            }
            else if (vUserOperationRightsModel.IsAdd && !vUserOperationRightsModel.IsEdit && AccountID != null)
            {
                return RedirectToAction("Index", "Error", new { Area = "" });
            }
            else if (!vUserOperationRightsModel.IsAdd && vUserOperationRightsModel.IsEdit && AccountID == null)
            {
                return RedirectToAction("Index", "Error", new { Area = "" });
            }
            #endregion 11.2 IsAdd, IsEdit Rights    

            #region 11.2 Fill Lables
            FillLabels(ControllerContext);
            #endregion 11.2 Fill Lables            

            #region 11.3 Dropdown List Fill Section
            FillDropDownList();
            #endregion 11.3 Dropdown List Fill Section

            #region 11.4 Set Control Default Value
            ACC_AccountModel AccountModel = new ACC_AccountModel();
            #endregion 11.4 Set Control Default Value

            if (AccountID != null || AccountID > 0)
            {
                ViewBag.Action = "Edit";

                //var d = balACC_Account.dbo_PR_ACC_Account_SelectByPk(AccountID).SingleOrDefault();
                var d = balACC_Account.dbo_PR_ACC_Account_SelectByPk(AccountID);

                //Mapper.Initialize(config => config.CreateMap<API_Consume.DAL.dbo_PR_ACC_Account_SelectByPK_Result, ACC_AccountModel>());
                //var vModel = AutoMapper.Mapper.Map<API_Consume.DAL.dbo_PR_ACC_Account_SelectByPK_Result, ACC_AccountModel>(d);

                return View("ACC_AccountAddEdit", d);
                //var data = await balACC_Account.ACC_Account_SelectByPk(AccountID);
                //return View("ACC_AccountAddEdit", data);
            }
            ViewBag.Action = "Add";
            return View("ACC_AccountAddEdit", AccountModel);
            //ViewBag.Action = "Add";
            //return View("ACC_AccountAddEdit",null);
        }
        #endregion 11.0 Page Load Event - Add/Edit

        #region 15.0 Save Button Event
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult _Save(ACC_AccountModel modelACC_Account)
        {
            try
            {
                #region Validate Field
                string errorMsg = "";
                if (modelACC_Account.AccountTypeID == null)
                {
                    errorMsg += "<li>Select Account Type</li>";
                }
                if (modelACC_Account.AccountGroupID == null)
                {
                    errorMsg += "<li>Enter  No</li>";
                }
                if (errorMsg != "")
                {
                    TempData["ErrorMessage"] = errorMsg;
                    return View("ACC_AccountAddEdit", modelACC_Account);
                }
                #endregion Validate Field

                #region Gather Data
                #endregion Gather Data
                modelACC_Account.xmlMST_Company = "<dtMST_Company><CompanyID>2</CompanyID></dtMST_Company><dtMST_Company><CompanyID>3</CompanyID></dtMST_Company>";

                if (modelACC_Account.AccountID == 0)
                {
                    bool vReturn = balACC_Account.dbo_PR_ACC_Account_Insert(modelACC_Account);
                    if (vReturn)
                    {
                        TempData["SuccessMessage"] = "Record Inserted Successfully..!";
                    }
                    else
                    {
                        TempData["ErrorMessage"] = "Some Error Has Occured..!";
                    }
                }
                else
                {
                    bool vReturn = balACC_Account.dbo_PR_ACC_Account_Update(modelACC_Account);
                    if (vReturn)
                    {
                        TempData["SuccessMessage"] = "Record Updated Successfully..!";
                    }
                    else
                    {
                        TempData["ErrorMessage"] = "Some Error Has Occured..!";
                    }
                }

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                return View("ACC_AccountAddEdit", modelACC_Account);
            }
        }
        #endregion 15.0 Save Button Event
    }
}

Log_09_Account/Areas/ACC/Views/Shared/_ACC_AccountList.cshtml
@using Log_09_Account.CF;
@using Log_09_Account.BAL;
@using Log_09_Account.DAL;
@using Log_09_Account.Areas.ACC.Models;
@using static Log_09_Account.DAL.ACC_AccountDALBase;
@model Tuple<ACC_AccountModel, PagedListPagerModel, List<dbo_PR_ACC_Account_SelectAll_Result>>

@{
    UserOperationRightsModel vUserOperationRightsModel = ViewBag.UserOperationRights;
}
<div class="card-body pt-0">
    <div class="row">
        <div class="col-md-12">
            @* <partial name="/Views/Error/_ucShowInfo.cshtml" /> *@
        </div>
    </div>
    <div>
        <a asp-area="ACC" asp-action="AddEdit" asp-controller="ACC_Account" class="btn btn-sm btn-success">
            <i class="fa fa-plus"></i> Add Account
        </a>
    </div>
    <div class="col-md-12" id="divCityList">


        <form id="hdFormUpdateCityList" class="" data-ajax="true" data-ajax-method="post" data-ajax-mode="replace" data-ajax-update="#SearchResult"
              data-ajax-success="OnSuccess(this.id,data, status, xhr);" data-ajax-failure="OnFailure(xhr, status, error);"
              asp-action="_SearchResult" asp-controller="ACC_Account" asp-area="ACC">
            @Html.AntiForgeryToken()
            <div class="row" style="margin-bottom: 10px;">
                <div class="col-md-7">
                    @* Page size: @Html.DropDownList("F_PageSize", Model.Item2.PageSizeList, new { @class = "form-select js-grid-hd-input", style = "display: inline; width: 65px; height: 30px; padding: 0px 4px; padding-top: 2px; padding-bottom: 6px;" }) *@
                    <div class="d-inline-bMEMk">@Html.Raw(Model.Item2.PageInfo)</div>
                </div>

            </div>
            <div class="row">
                <div class="col-md-12">
                    <input type="hidden" id="GoToPageNo" class="js-grid-hd-input" name="F_PageNo" value="@(Model.Item1.F_PageNo)" />
                </div>
            </div>
        </form>
        <div class="table-responsive">
            <table class="table table-bordered table-hover" id="tblList">
                <thead class="table-secondary">
                    <tr class="fw-bold">
                        <th width="10%">A/C Type</th>
                        <th width="8%"> Account Name</th>
                        <th width="10%">A/C print Name</th>
                        <th width="8%">A/C Group</th>
                        <th>OB On</th>
                        <th>Amount</th>
                        <th width="5%">Active</th>
                        <th width="8%">RMC</th>
                        <th width="8%">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        int i = 0;
                    }
                    @if (Model.Item3.Count == 0)
                    {
                        <tr class="text-center">
                            <td colspan="8">No records found...!</td>
                        </tr>
                    }
                    @foreach (var item in Model.Item3)
                    {
                        i++;
                        <tr>
                            <td>@item.AccountTypeName</td>
                            <td>@item.AccountName</td>
                            <td>@item.AccountPrintName</td>
                            <td>@item.AccountGroupName</td>
                            <td>@item.OBon</td>
                            <td>@item.OBAmount</td>
                            <td>@item.IsActive</td>
                            <td>@item.IsRCM</td>
                            
                            <td class="text-center">
                                @if (vUserOperationRightsModel.IsEdit)
                                {
                                    <span data-bs-toggle="tooltip" data-bs-placement="left" title="Edit">
                                        <a asp-area="ACC" asp-action="AddEdit" asp-controller="ACC_Account" asp-route-AccountID="@item.AccountID" class="btn btn-primary btn-icon btn-elevate btn-sm">
                                            <i class="fa fa-pencil"></i>
                                        </a>
                                    </span>
                                }

                                @if (vUserOperationRightsModel.IsDelete)
                                {
                                    <form method="post" asp-area="ACC" asp-action="_Delete" asp-controller="ACC_Account" style="display: inline;">
                                        @Html.AntiForgeryToken()
                                        <input type="hidden" name="AccountID" value="@item.AccountID" />
                                        <a class="btn btn-danger btn-icon btn-elevate btn-sm js-bb-confirm-delete" data-bs-toggle="tooltip" data-bs-placement="left" title="Delete"><i class="fa fa-trash"></i></a>
                                    </form>
                                }
                            </td> 
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="text-end pull-end">
            @* <partial name="/Views/Shared/_GeneratePager.cshtml" model="@Model.Item2" /> *@
        </div>
    </div>
</div>

Log_09_Account/Areas/ACC/Views/Shared/_ACC_AccountListFilterForm.cshtml
@using Log_09_Account.CF;
@using Log_09_Account.BAL;
@model Log_09_Account.Areas.ACC.Models.ACC_AccountModel;

<div class="container-fluid px-4 pt-4">
    <div class="row">
        <div class="col-sm-12 col-xl-12">
            <div class="bg-light rounded h-100 p-4">
                <h6 class="mb-4">Filtters</h6>
                <form id="filterForm" class="filter-form" data-ajax="true" data-ajax-method="post" data-ajax-mode="replace"
                      data-ajax-update="#SearchResult" data-ajax-success="OnSuccess(this.id,data, status, xhr);"
                      data-ajax-failure="OnFailure(xhr, status, error);" asp-action="_SearchResult" asp-controller="ACC_Account"
                      asp-area="ACC">
                    @Html.AntiForgeryToken()

                    <div class="row">
                        <div class="col-4">
                            <div class="mb-3">
                                <div class="input-group mb-3">
                                    @* drop down *@
                                    <span class="input-group-text" id="basic-addon1">
                                        <i class="fas fa-search"></i>
                                    </span>
                                    <select class="form-control" data-control="select2" asp-for="F_AccountTypeID"
                                            asp-items="@(new SelectList(ViewBag.AccountTypeList,"AccountTypeID","AccountTypeName"))">
                                        <option value="">Select AccounType</option>
                                    </select>
                                    @Html.ValidationMessageFor(m => m.F_AccountTypeID, "", new { @class = "form-text text-danger" })

                                </div>
                            </div>
                        </div>
                        <div class="col-4">
                            <div class="mb-3">
                                <div class="input-group mb-3">
                                    @* textbox *@
                                    <span class="input-group-text" id="basic-addon1">
                                        <i class="fas fa-search"></i>
                                    </span>
                                    <input type="text"
                                           class="form-control"
                                           placeholder="Enter Account Name"
                                           asp-for="F_AccountName" />
                                    @Html.ValidationMessageFor(m => m.F_AccountName, "", new { @class = "form-text text-danger" })
                                </div>
                            </div>
                        </div>
                        <div class="col-4">
                            <div class="mb-3">
                                <div class="input-group mb-3">
                                    @* textbox *@
                                    <span class="input-group-text" id="basic-addon1">
                                        <i class="fas fa-search"></i>
                                    </span>
                                    <input type="text"
                                           class="form-control"
                                           placeholder="Enter Account Print Name"
                                           asp-for="F_AccountPrintName" />
                                    @Html.ValidationMessageFor(m => m.F_AccountPrintName, "", new { @class = "form-text text-danger" })
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-4">
                            <div class="mb-3">
                                <div class="input-group mb-3">
                                    @* drop down *@
                                    <span class="input-group-text" id="basic-addon1">
                                        <i class="fas fa-search"></i>
                                    </span>
                                    <select class="form-control" data-control="select2" asp-for="F_AccountGroupID"
                                            asp-items="@(new SelectList(ViewBag.AccountGroupList,"AccountGroupID","AccountGroupName"))">
                                        <option value="">Select AccountGroup</option>
                                    </select>
                                    @Html.ValidationMessageFor(m => m.F_AccountGroupID, "", new { @class = "form-text text-danger" })
                                </div>
                            </div>
                        </div>
                        <div class="col-4 d-flex">
                            <div id="AllOB" class="">
                                <input class="form-check-input"
                                       asp-for="F_IsZero"
                                       type="radio"
                                       name="F_IsZero"
                                       id="AllOB"
                                       value=""
                                       checked
                                      />
                                <label class="form-check-label mr-3" for="AllOB">
                                    All
                                </label>
                            </div>
                            <div id="NonZeroOB" class="">
                                <input class="form-check-input"
                                       asp-for="F_IsZero"
                                       type="radio"
                                       name="F_IsZero"
                                       id="NonZeroOB"
                                       value="false"
                                      />
                                <label class="form-check-label" for="NonZeroOB">
                                    Non Zero OB
                                </label>
                            </div>
                            <div id="ZeroOB" class="">
                                <input class="form-check-input"
                                       asp-for="F_IsZero"
                                       type="radio"
                                       name="F_IsZero"
                                       id="ZeroOB"
                                       value="true"
                                      />
                                <label class="form-check-label" for="ZeroOB">
                                    Zero OB
                                </label>
                            </div>
                        </div>
                        <div class="col-4 d-flex">
                            <div id="AllCR" name="CRGroup" class="">
                                <input class="form-check-input"
                                       asp-for="@Model.F_IsCR"
                                       type="radio"
                                       name="F_IsCR"
                                       id="AllCR"
                                       value=""
                                       checked
                                      />
                                <label class="form-check-label mr-3" for="AllCR">
                                    All
                                </label>
                            </div>
                            <div id="CR" name="CRGroup" class="">
                                <input class="form-check-input"
                                       asp-for="@Model.F_IsCR"
                                       type="radio"
                                       name="F_IsCR"
                                       id="CR"
                                       value="true"
                                      />
                                <label class="form-check-label" for="CR">
                                    CR
                                </label>
                            </div>
                            <div id="DR" name="CRGroup" class="">
                                <input class="form-check-input"
                                       asp-for="@Model.F_IsCR"
                                       type="radio"
                                       name="F_IsCR"
                                       id="DR"
                                       value="false"
                                      />
                                <label class="form-check-label" for="DR">
                                    DR
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-4 d-flex">
                            <div id="AllRCM" class="">
                                <input class="form-check-input"
                                        asp-for="@Model.F_IsRCM"
                                       type="radio"
                                       name="F_IsRCM"
                                       id="AllRCM"
                                       value=""
                                       checked />
                                <label class="form-check-label mr-3" for="AllRCM">
                                    All
                                </label>
                            </div>
                            <div id="NotRCM" class="">
                                <input class="form-check-input"
                                       asp-for="@Model.F_IsRCM"
                                       type="radio"
                                       name="F_IsRCM"
                                       id="NotRCM"
                                       value="false"
                                      />
                                <label class="form-check-label" for="NotRCM">
                                    Not RCM
                                </label>
                            </div>
                            <div id="RCM" class="">
                                <input class="form-check-input"
                                       asp-for="@Model.F_IsRCM"
                                       type="radio"
                                       name="F_IsRCM"
                                       id="RCM"
                                       value="true"
                                      />
                                <label class="form-check-label" for="RCM">
                                    RCM
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="row mt-3">
                        <div class="col-12">
                            <button type="submit" class="btn btn-primary">
                                Search
                            </button>

                            <button type="submit" class="btn btn-danger">
                                Clear
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>